name: Data Pipeline Workflow

on:
  push:
    paths:
      - data/**

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DVC
        run: pip install dvc

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure DVC Remote
        run: dvc remote modify my_remote s3://my-bucket/data

      - name: Pull Latest Data
        run: dvc pull

      - name: Execute Data Pipeline
        run: dvc repro