name: Machine Learning Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  data_preprocessing:
    name: Process data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Preprocess data
        run: python src/preprocess_data.py

  model_training:
    name: Train model
    runs-on: ubuntu-latest
    needs: data_preprocessing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python src/train_model.py

  evaluate_model:
    name: Evaluate model
    runs-on: ubuntu-latest
    needs: model_training
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Evaluate model
        run: python src/evaluate_model.py

  get_predictions:
    name: Get predictions
    runs-on: ubuntu-latest
    needs: model_training
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate predictions
        run: python src/predict.py